version: "3.9"

services:
 postgres1:
    image: postgres:14.1-alpine
    container_name: postgres1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - postgres1:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - postgres


 postgres2:
   image: postgres:14.1-alpine
   container_name: postgres2
   restart: always
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - 5434:5432
   volumes:
     - postgres2:/var/lib/postgresql/data
     - ./script.sql:/docker-entrypoint-initdb.d/script.sql
   networks:
     - postgres

 postgres3:
   image: postgres:14.1-alpine
   container_name: postgres3
   restart: always
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - 5435:5432
   volumes:
     - postgres3:/var/lib/postgresql/data
     - ./script.sql:/docker-entrypoint-initdb.d/script.sql
   networks:
     - postgres

volumes:
  postgres1:
    driver: local
  postgres2:
    driver: local
  postgres3:
    driver: local


networks:
  postgres:
    driver: bridge